### ISSUE TITLE
Suggestion: export ApiDocumentation

### ISSUE THREAD

**Issue by postatum** [advanced-rest-client/api-documentation#21]
Hi.

It would be nice if `ApiDocumentation` was exported. I'm trying to create a custom `api-documentation` by extending `ApiDocumentation` and I can't import `ApiDocumentation` because it's not exported.

Thanks.

**Comment by jarrodek** [comment]
This component wasn't upgraded to this like the rest of the components just yet. @TwoPlusTwoOne could you or @carowright add this to the tasks list?

**Comment by postatum** [comment]
Hi @jarrodek. Thanks for paying attention to this issue!

Any updates on when it will be fixed? It's blocking some of my work.

**Comment by TwoPlusTwoOne** [comment]
Working on it today

**Comment by postatum** [comment]
> Working on it today

Huge thanks!
