### ISSUE TITLE
Changing inner elements structure

### ISSUE THREAD

**Issue by postatum** [advanced-rest-client/api-documentation#4]
Hi @jarrodek.

Is there a way to change inner `<api-documentation>` elements structure when it's used in an html file [like so](https://github.com/advanced-rest-client/api-documentation#in-an-html-file)?

Maybe there's a way to provide a custom html template or something?

I need to hide some elements (next/prev section) inside `<api-documentation>` and change order of others ().

**Comment by jarrodek** [comment]
No, there is no option to disable navigation elements right now. Order (information architecture) cannot be changed as well.
I talked to Jonathan, i will introduce an option to hide navigation.

**Comment by jarrodek** [comment]
You can now set `noBottomNavigation` attribute to remove the nav.

**Comment by postatum** [comment]
> You can now set `noBottomNavigation` attribute to remove the nav.

Cool, thanks. Also thanks for the "module" prop in package.json!

**Comment by postatum** [comment]
Hi @jarrodek.

Is there still no way to customize the templates? Maybe it's possible to pass custom templates to the lib?

Thanks
